2024-12-03 14:26:03,604 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\W10\Desktop\sky_python\urban\test_12_4\tests_12_4.py", line 30, in test_run
    runner = Runner(None)
             ^^^^^^^^^^^^
  File "C:\Users\W10\Desktop\sky_python\urban\test_12_4\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано NoneType
2024-12-03 14:26:03,606 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\W10\Desktop\sky_python\urban\test_12_4\tests_12_4.py", line 20, in test_walk
    runner = Runner('Name', -3)
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\W10\Desktop\sky_python\urban\test_12_4\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -3
